services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=transactionstore'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=dian'
    ports:
      - '5434:5434'
    command: postgres -c 'port=5434'